#' Example BAM-files
#'
#' A set of BAM-files for demonstration purposes of the functions in package \pkg{breakpointR}.
#'
#' @docType data
#' @name example_bams
#' @aliases bams
#' @format A BAM files with aligned reads.
#' @source A lyphoblastoid cell line of Puerto Rican origin (HG00731). Raw reads were aligned to the GRCh38/hg38 reference assembly. The file has been downsampled to 20\% of the coverage to reduce the file size. 
#' @references \url{https://www.biorxiv.org/content/early/2017/09/23/193144}
NULL

#' Results for example BAM-files
#'
#' Localized breakpoints in example BAM-files, generated by the \pkg{breakpointR} package. 
#'
#' @docType data
#' @name example_results
#' @aliases results
#' @format Files containing \code{BreakPoint} object.
#' @source A lyphoblastoid cell line of Puerto Rican origin (HG00731). Raw reads were aligned to the GRCh38/hg38 reference assembly.
#' @references \url{https://www.biorxiv.org/content/early/2017/09/23/193144}
NULL
